version: '3.4'

services:
  emiko:
    image: emiko
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      # args:
        # - DB_URL=file:data/asd.db
    environment:
      NODE_ENV: production
      JWT_SECRET: secret
  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    # command: caddy fmt --overwrite /etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
      # - "443:443/udp" #HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
