version: '3.4'

services:
  emiko:
    image: emiko
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DB_URL: file:data/asd.db
      JWT_SECRET: asd
    # ports:
    #   - 80:3000
