services:
  emiko:
    image: emiko
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # NODE_ENV: production
      # DB_URL: file:/data/emiko.db
      # DATA_PATH: /data
      JWT_SECRET: secret
    volumes:
      - ./data:/data
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      # - "443:443/udp" #HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
